name: camep
description: Car media player.

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable:
  flutter_bloc:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  build_runner:
  bloc_test:

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
